### PR TITLE
Use vue supabase as dependency

### PR DESCRIPTION
**Pull request by sduduzog**
## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by scottrobertson** [comment]
@sduduzog 1.0.6 of vue-supabase has been released with your changes.

**Comment by sduduzog** [comment]
I will update this PR  asap

**Comment by scottrobertson** [comment]
@sduduzog this ready to go now?

**Comment by sduduzog** [comment]
I wanted to test the package on my project first, will do so in an hours time

**Comment by sduduzog** [comment]
good to go @scottrobertson

**Comment by scottrobertson** [comment]
1.0.8 released

**Comment by scottrobertson** [comment]
@sduduzog we should also check this does not mess up #1 actually. Forgot about that.

**Comment by sduduzog** [comment]
@scottrobertson definitely did. But you saying it again makes me nervous so I'll do the check... In fact, it is why we had to use commonjs for vue-supabase.

**Comment by scottrobertson** [comment]
@sduduzog just an FYI, I am using this in one of my projects now, and it's working nicely :) good job on this.

**Pull request merged**
